# $ python scripts/main.py fit -c configs/train.yaml --ckpt_path 'path'
# lightning.pytorch==2.1.2
seed_everything: 2894872274
trainer:
  accelerator: auto
  strategy: auto
  devices: [0]
  num_nodes: 1
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      save_dir: ./lightning
      offline: false
      project: srunet
      log_model: true
      prefix: ''
      group: 'pixshuf-up'
  fast_dev_run: false
  max_epochs: 100
  max_steps: -1
  overfit_batches: 0.0
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 1
  inference_mode: true
  use_distributed_sampler: true
  detect_anomaly: false
  barebones: false
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
model:
  generator:
    class_path: SRUnet
    init_args:
      residual: true
      scale_factor: 2
  discriminator:
    class_path: models.Discriminator
    init_args:
      kernel_size: 3
      n_channels: 32
      n_blocks: 8
      fc_size: 1024
  lpips_loss_weight: 1.0
  ssim_loss_weight: 1.0
  bce_loss_weight: 0.001
data:
  hq_path: /home/DATASETS/BVI_DVC/frames_HQ
  lq_path: /home/DATASETS/BVI_DVC/frames/frames_CRF_27
  extension: png
  path_filter: '1088'
  patch_size: 64
  train_pct: 0.8
  use_ar: true
  dataset_upscale_factor: 2
  batch_size: 32
